#!/usr/bin/env python3
"""run the v3.0 argument-template envelope sweep — Phase S2 §5.

per INSTRUCTION_BORON_S2.md §5.1: 8 templates × 5 grid points along a
low-π → high-π diagonal × 30 seeds = 1200 runs.

each cell:
    σ = σ_max * σ_fraction
    π = π_max * π_fraction
    base_opp = base_opp_floor   (envelope minimum)
    exit_cost = exit_cost_baseline   (envelope minimum)

where (σ_max, π_max, base_opp_floor, exit_cost_baseline) come from
src/religion_fundamentalism_abm_v3_0.ENVELOPE_TABLE.

usage:
    python scripts/run_v3_0_envelope_sweep.py --dry_run
    python scripts/run_v3_0_envelope_sweep.py --workers 60
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

# load v3.0 envelope from canonical source — single source of truth
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
import religion_fundamentalism_abm_v3_0 as v30  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = REPO_ROOT / "src" / "religion_fundamentalism_abm_v3_0.py"
RESULTS_ROOT = REPO_ROOT / "results" / "v3_0_envelope_sweep"

# §5.1: 5 grid points along low-π → high-π diagonal
SIGMA_FRACTIONS = (0.500, 0.625, 0.750, 0.875, 1.000)
PI_FRACTIONS    = (0.200, 0.400, 0.600, 0.800, 1.000)
N_SEEDS = 30
SEEDS = tuple(range(1, N_SEEDS + 1))
TEMPLATES = ("T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8")

# v2.5 standing protocol cell parameters
STEPS = 450
N = 350
GRAPH = "scale_free"


def gridCells():
    """yield (template, grid_idx, sigma, pi, base_opp_floor, exit_cost_baseline) tuples.

    one tuple per (template, grid_position) — 8 × 5 = 40 cells.
    """
    for template in TEMPLATES:
        sigma_max, pi_max, base_opp_floor, exit_cost_baseline = v30.ENVELOPE_TABLE[template]
        for grid_idx, (sf, pf) in enumerate(zip(SIGMA_FRACTIONS, PI_FRACTIONS)):
            sigma = round(sigma_max * sf, 4)
            pi = round(pi_max * pf, 4)
            yield (template, grid_idx, sigma, pi, base_opp_floor, exit_cost_baseline)


def buildCommand(template: str, grid_idx: int, sigma: float, pi: float,
                 base_opp: float, exit_cost: float, seed: int,
                 outdir: Path, python_bin: str) -> list:
    return [
        python_bin, str(MODEL_PATH),
        "--outdir", str(outdir),
        "--steps", str(STEPS),
        "--n", str(N),
        "--graph", GRAPH,
        "--seed", str(seed),
        "--argument_template", template,
        "--sigma", f"{sigma:.4f}",
        "--pi_reward", f"{pi:.4f}",
        "--exit_opportunity_base", f"{base_opp:.4f}",
        "--exit_cost", f"{exit_cost:.4f}",
        "--no_movie",
    ]


def runOne(template: str, grid_idx: int, sigma: float, pi: float,
           base_opp: float, exit_cost: float, seed: int, python_bin: str) -> tuple:
    """run a single cell. resumable: skip if both metrics + agent_summary exist."""
    outdir = RESULTS_ROOT / template / f"grid_{grid_idx}" / f"seed_{seed:02d}"
    metrics_path = outdir / "metrics.csv"
    agent_path = outdir / "agent_summary.csv"
    if metrics_path.exists() and agent_path.exists():
        return (template, grid_idx, seed, "SKIP_EXISTS")
    outdir.mkdir(parents=True, exist_ok=True)
    cmd = buildCommand(template, grid_idx, sigma, pi, base_opp, exit_cost,
                       seed, outdir, python_bin)
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL)
        return (template, grid_idx, seed, "OK")
    except subprocess.CalledProcessError as exc:
        return (template, grid_idx, seed, f"FAIL rc={exc.returncode}")


def emitDryRun(out_path: Path) -> None:
    """write grid-coordinate inspection to synthesis/envelope_sweep_v1/_dry_run.md."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Phase S2 envelope sweep — dry-run grid coordinates",
        "",
        "**Generated by:** `scripts/run_v3_0_envelope_sweep.py --dry_run`",
        "**Source:** `src/religion_fundamentalism_abm_v3_0.ENVELOPE_TABLE` (canonical, sourced from `INSTRUCTION_BORON_S2.md` §3.3).",
        "",
        f"**Sweep size:** {len(TEMPLATES)} templates × {len(SIGMA_FRACTIONS)} grid cells × {N_SEEDS} seeds = "
        f"**{len(TEMPLATES) * len(SIGMA_FRACTIONS) * N_SEEDS} runs**.",
        "",
        f"**Per-run params:** steps={STEPS}, n={N}, graph={GRAPH}, no_movie. seeds={list(SEEDS)}.",
        "",
        "**Grid fractions** (per §5.1):",
        "",
        "| grid | σ_fraction | π_fraction |",
        "|------|------------|------------|",
    ]
    for i, (sf, pf) in enumerate(zip(SIGMA_FRACTIONS, PI_FRACTIONS)):
        lines.append(f"| {i}    | {sf:.3f}      | {pf:.3f}      |")

    lines.extend([
        "",
        "## Concrete (σ, π, base_opp, exit_cost) per cell",
        "",
        "Each cell below corresponds to 30 seeded runs. base_opp_floor and exit_cost_baseline are envelope minima per §3.3 (the case-scorer is free to push these higher; the sweep tests at the floor).",
        "",
        "| Template | grid | σ | π | base_opp | exit_cost |",
        "|----------|------|---|---|----------|-----------|",
    ])

    for template, grid_idx, sigma, pi, base_opp, exit_cost in gridCells():
        lines.append(
            f"| {template}       | {grid_idx}    | {sigma:.4f} | {pi:.4f} | "
            f"{base_opp:.2f}     | {exit_cost:.2f}      |"
        )

    lines.extend([
        "",
        "## Envelope ceilings (for cross-check)",
        "",
        "| Template | σ_max | π_max | base_opp_floor | exit_cost_baseline |",
        "|----------|-------|-------|----------------|--------------------|",
    ])
    for template in TEMPLATES:
        smax, pmax, bopp, ecb = v30.ENVELOPE_TABLE[template]
        lines.append(
            f"| {template}       | {smax:.2f}  | {pmax:.2f}  | "
            f"{bopp:.2f}           | {ecb:.2f}               |"
        )

    lines.extend([
        "",
        "## Validation",
        "",
        "- Highest σ across all cells: T1/T2 grid 4 — σ=0.65 (= T1 σ_max, by design).",
        "- Highest π across all cells: T4 grid 4 — π=0.45 (= T4 π_max, by design).",
        "- Lowest σ across all cells: T7 grid 0 — σ=0.10 (= 0.50 × T7 σ_max=0.20).",
        "- Lowest π across all cells: T7 grid 0 — π=0.01 (= 0.20 × T7 π_max=0.05).",
        "",
        "All cell σ, π values lie strictly within their template's envelope (validated by `validateEnvelope()` in `religion_fundamentalism_abm_v3_0.py` at run time; out-of-envelope cells would raise ValueError before any simulation step).",
        "",
        "## Output layout",
        "",
        "Per-run metrics will land at:",
        "",
        "```",
        "results/v3_0_envelope_sweep/<template>/grid_<i>/seed_<s>/",
        "├── metrics.csv          # per-step metrics (450 rows × ~38 cols, includes active_punish_rate)",
        "└── agent_summary.csv    # per-agent terminal state (350 rows)",
        "```",
        "",
        "Resumable: existing (metrics.csv + agent_summary.csv) cells are skipped on re-run.",
        "",
        "## Wall-clock estimate",
        "",
        "Per CLAUDE.md, v2.5 confirmatory sweep is 4–6 hours for 360 runs on 64 cores (~50 s/run, single-core per process). 1200 runs at WORKERS=60 → ~50 s/run × 1200 / 60 ≈ 17 minutes/batch × 20 batches → roughly 13–20 hours wall clock. ABM is CPU-only; GPUs idle.",
        "",
    ])
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry_run", action="store_true",
                    help="print grid coordinates to stdout + write _dry_run.md, no simulation.")
    ap.add_argument("--dry_run_path", type=str,
                    default=str(REPO_ROOT / "synthesis" / "envelope_sweep_v1" / "_dry_run.md"),
                    help="where to write the dry-run inspection markdown.")
    ap.add_argument("--workers", type=int, default=60,
                    help="ThreadPoolExecutor max_workers (default 60; standing protocol).")
    ap.add_argument("--python_bin", type=str,
                    default=str(REPO_ROOT / ".venv" / "bin" / "python"),
                    help="python interpreter to use for subprocess calls.")
    args = ap.parse_args()

    cells = list(gridCells())
    n_runs = len(cells) * N_SEEDS
    print(f"sweep size: {len(TEMPLATES)} templates × {len(SIGMA_FRACTIONS)} grid × "
          f"{N_SEEDS} seeds = {n_runs} runs")
    print(f"output root: {RESULTS_ROOT}")
    print(f"workers: {args.workers}")

    if args.dry_run:
        emitDryRun(Path(args.dry_run_path))
        print(f"\nwrote dry-run inspection to {args.dry_run_path}")
        print("\nfirst 5 cells:")
        for i, c in enumerate(cells[:5]):
            t, g, s, p, b, e = c
            print(f"  {t} grid_{g}: σ={s:.4f} π={p:.4f} base_opp={b:.2f} exit_cost={e:.2f}")
        print(f"  ... ({len(cells)} cells total)")
        return 0

    # real sweep: ThreadPoolExecutor over all (cell × seed) tasks
    tasks = []
    for template, grid_idx, sigma, pi, base_opp, exit_cost in cells:
        for seed in SEEDS:
            tasks.append((template, grid_idx, sigma, pi, base_opp, exit_cost, seed))

    print(f"queuing {len(tasks)} tasks across {args.workers} workers...")
    done = 0
    skipped = 0
    failed = 0
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = [ex.submit(runOne, *task, args.python_bin) for task in tasks]
        for fut in as_completed(futs):
            result = fut.result()
            done += 1
            status = result[3]
            if status.startswith("FAIL"):
                failed += 1
                print(f"  FAIL: {result[0]} grid_{result[1]} seed_{result[2]:02d} — {status}")
            elif status == "SKIP_EXISTS":
                skipped += 1
            if done % 50 == 0 or done == len(tasks):
                print(f"  progress: {done}/{len(tasks)}  "
                      f"(ok={done - skipped - failed}, skip={skipped}, fail={failed})")

    print(f"\ndone: {done} tasks, {failed} failed, {skipped} skipped (already existed).")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
